### PR TITLE
Resolved Conflicts and Modified Models

### PR DESCRIPTION
**Pull request by preet4737**

### CODE REVIEW

**Comment by vixrant** [comment]
@amoghparab247 `test.py` is not working.

**Comment by amoghparab247** [comment]
Remove class Menu test from test.py.

**Comment by aayushkothari11** [comment]
@preet4737 Solve the conflict, I will merge the PR then.

**Comment by preet4737** [comment]
> class MenuItemSerializer(serializers.ModelSerializer):
> class Meta:
> model = MenuItem
> fields = (
> "url",
> "id",
> "name",
> "price",
> "is_available",
> "preparation_time",
> "options",
> "category",
> )
> fields = ("id", "name", "price", "is_available", "preparation_time", "options")
> 
> Please resolve this @preet4737
Did not notice this.I will solve it.

**Pull request merged**
